plugins {
    id "idea"
    id "java"
    id "maven-publish"
    id "signing"
}

group "com.swacky.${modId}"
version "${project.name}+${mcV}"

base {
    archivesName.set "${modId}-${modV}"
}

java {
    JavaLanguageVersion javaVersion = JavaLanguageVersion.of(javaV);
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    toolchain.languageVersion = javaVersion

    withJavadocJar()
    withSourcesJar()
}

processResources {
    var replaceProperties = [
            modId          : modId,
            packFormatMinV : packFormatMinV,
            packFormatMaxV : packFormatMaxV
    ]

    inputs.properties replaceProperties

    filesMatching(["pack.mcmeta", "resourcepacks/*/pack.mcmeta"]) {
        expand replaceProperties
    }
}

repositories {
    maven {
        name = "Sponge"
        url = "https://repo.spongepowered.org/repository/maven-public"
    }
}

dependencies {
    implementation "io.github.swackyy:ohmega-${project.name}:${ohmegaV}-mc${mcV}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set JavaLanguageVersion.of(javaV).asInt()
}

tasks.withType(Javadoc).configureEach {
    options.quiet()
}

jar {
    exclude "**/.cache"
}

tasks.named("sourcesJar", Jar) {
    exclude "**/.cache"
}

tasks.named("compileTestJava") {
    enabled = false
}

tasks.named("processTestResources") {
    enabled = false
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

["apiElements", "runtimeElements", "sourcesElements", "javadocElements"].each { variant ->
    configurations."${variant}".outgoing {
        capability "${group}:${base.archivesName.get()}:${version}"
        capability "${group}:${modId}-${project.name}-${mcV}:${version}"
        capability "${group}:${modId}:$version"
    }
}