plugins {
    id "fabric-loom" version "${pluginLoomV}" apply false
    id "idea"
    id "net.minecraftforge.gradle" version "${pluginForgeV}" apply false
    id "net.neoforged.moddev" version "${pluginNeoV}" apply false
}

idea {
    module {
        downloadJavadoc true
        downloadSources true
    }
}

File secretsFile = file("secrets.properties")

if (secretsFile.exists()) {
    secretsFile.withInputStream { stream ->
        {
            Properties secrets = new Properties()

            secrets.load(stream)
            secrets.forEach {
                key, value -> project.ext.set((String) key, value)
            }
        }
    }

    // Publishes the mod to the following platforms:
    // CurseForge
    // Modrinth
    tasks.register("completeRelease") {
        group = "publishing"

        subprojects.each { sub ->
            sub.plugins.withType(MavenPublishPlugin).configureEach {
                dependsOn sub.tasks.named("publish")

                if (sub.name != "common") {
                    dependsOn sub.tasks.named("publishMods")
                }
            }
        }
    }
}