org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

javaV=21
mcV=1.21.11
packFormatMinV=1
packFormatMaxV=94
# https://projects.neoforged.net/neoforged/neoform
neoFormV=20251209.172050
loaderFabricVRange=>=0.15
loaderForgeVRange=[61,)
loaderNeoVRange=[21.11,)
loaderFabricForgeConfigApiPortVRange=>=21.11

loaderFabricOhmegaVRange=>=1.5
ohmegaVRange=[1.5,)

loaderFabricV=0.18.4
loaderForgeV=61.0.8
loaderNeoV=21.11.37-beta
loaderFabricApiV=0.141.2
loaderFabricForgeConfigApiPortV=21.11.1
loaderFabricModMenuV=17.0.0-beta.2
ohmegaV=1.5.11

mapsMcV=1.21.11
mapsV=2025.12.20

modV=1.3.1

pluginLoomV=1.13-SNAPSHOT
pluginForgeV=[6.0.46, 6.2)
pluginNeoV=2.0.124

license=All rights reserved
modName=ElytraAccessory
modNameDisplay=Elytra Accessory
modId=elytra_accessory
modAuthors=swacky
modAuthorsDisplay=Swacky_

gitUrl=https://github.com/Swackyy/ElytraAccessory
curseUrl=https://curseforge.com/minecraft/mc-mods/elytra-accessory
discordUrl=https://discord.gg/B9669WDmZk
modrinthUrl=https://modrinth.com/mod/elytra-accessory
modDesc=Allows Elytras to be equipped as an accessory (Ohmega API)
modDescSrc=View the source code here
modDescDiscord=Discord server