org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
org.gradle.jvmargs=-Xmx8G

net.minecraftforge.gradle.merge-source-sets=true

javaV=25

mcV=26.1.2
mcVRangeMin=26.1

packFormatMinV=1
packFormatMaxV=101

loaderFabricVRange=>=0.15
loaderForgeVRange=[62,)
loaderNeoVRange=[26.1,)
loaderFabricOhmegaVRange=>=1.6-beta.10
ohmegaVRange=[1.6-beta.10, 1.7)

loaderFabricV=0.19.2
loaderForgeV=64.0.8
loaderNeoV=26.1.2.68-beta
loaderFabricApiV=0.150.0
loaderFabricModMenuV=18.0.0-beta.1
ohmegaV=1.6.0-beta.10

modV=1.3.4

pluginLoomV=1.16-SNAPSHOT
pluginForgeV=7.0.25
pluginNeoV=2.0.141

license=All rights reserved
modName=ElytraAccessory
modNameDisplay=Elytra Accessory
modId=elytra_accessory
modAuthors=swacky
modAuthorsDisplay=Swackyy

gitUrl=https://github.com/Swackyy/ElytraAccessory
curseUrl=https://curseforge.com/minecraft/mc-mods/elytra-accessory
discordUrl=https://discord.gg/B9669WDmZk
modrinthUrl=https://modrinth.com/mod/elytra-accessory
modDesc=Allows Elytras to be equipped as an accessory (Ohmega API)
modDescSrc=View the source code here
modDescDiscord=Discord server