modLoader="javafml"
loaderVersion="[51,53)"
license="All rights reserved"
[[mods]]
modId="elytraaccessory"
version="${file.jarVersion}"
displayName="Elytra Accessory"
logoFile= "elytraaccessory.png"
authors="Developer: Swacky_"
description='''Allows Elytras to be equipped as an accessory (Ohmega API)'''
[[dependencies.elytraaccessory]]
modId="forge"
mandatory=true
versionRange="[51,53)"
ordering="NONE"
side="BOTH"
[[dependencies.elytraaccessory]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.elytraaccessory]]
modId="ohmega"
mandatory=true
versionRange="[1.2.1,)"
ordering="BEFORE"
side="BOTH"
