plugins {
    id "loader"
    id "net.fabricmc.fabric-loom" version "${pluginLoomV}"
}

loom {
    runs {
        configureEach {
            setConfigName "Fabric ${it.name.capitalize()}"

            ideConfigGenerated = true
            runDir = "run"
        }

        client {
            client()

            programArgs "--username", "Dev"
        }

        server {
            server()
        }
    }
}

repositories {
    maven {
        name = "Config API"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven"
    }

    maven {
        name = "ModMenu"
        url = "https://maven.terraformersmc.com/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${mcV}"

    implementation "net.fabricmc:fabric-loader:${loaderFabricV}"
    implementation "net.fabricmc.fabric-api:fabric-api:${loaderFabricApiV}+${mcV}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${loaderFabricForgeConfigApiPortV}"
    //implementation "com.terraformersmc:modmenu:${loaderFabricModMenuV}"
}

fabricApi {
    configureDataGeneration {
        outputDirectory = file(project(":loader:common").sourceSets.main.resources.getSourceDirectories().getFiles()[1].getAbsolutePath())
    }
}

tasks.withType(Jar).configureEach {
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}